# Generated by Django 5.1.2 on 2024-10-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_musician_remove_feeding_cat_music_delete_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='tool',
            field=models.ManyToManyField(to='main_app.tool'),
        ),
    ]
